/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

var hagiasofiaDesc = "Hagia Sophia, is a former Orthodox patriarchal basilica, later a mosque, and now a museum in Istanbul, Turkey. From the date of its dedication in 360 until 1453, it served as an Eastern Orthodox cathedral and seat of the Patriarchate of Constantinople, except between 1204 and 1261, when it was converted to a Roman Catholic cathedral under the Latin Empire. The building was a mosque from 29 May 1453 until 1931, when it was secularized. It was opened as a museum on 1 February 1935.<br/>" +
"The Church was dedicated to the Logos, the second person of the Holy Trinity, its dedication feast taking place on 25 December, the anniversary of the Birth of the incarnation of the Logos in Christ. Although it is sometimes referred to as Sancta Sophia (as though it were named after Saint Sophia), sophia is the phonetic spelling in Latin of the Greek word for wisdom – the full name in Greek being Ναός τῆς Ἁγίας τοῦ Θεοῦ Σοφίας, 'Shrine of the Holy Wisdom of God'.<br/>" +
"Famous in particular for its massive dome, it is considered the epitome of Byzantine architecture and is said to have 'changed the history of architecture.' It remained the world's largest cathedral for nearly a thousand years thereafter, until Seville Cathedral was completed in 1520. The current building was originally constructed as a church between 532 and 537 on the orders of the Byzantine Emperor Justinian and was the third Church of the Holy Wisdom to occupy the site, the previous two having both been destroyed by rioters. It was designed by the Greek scientists Isidore of Miletus, a physicist, and Anthemius of Tralles, a mathematician.";

var umayyadDesc = "The Umayyad Mosque, also known as the Great Mosque of Damascus (Arabic: جامع بني أمية الكبير‎, Romanization Ğām' Banī 'Umayya al-Kabīr) or formerly the Basilica of Saint John the Baptist (Greek: Βασιλική του Αγίου Ιωάννη του Βαπτιστή, transliteration Vasilikí tou Agíou Ioánni tou Vaptistí), located in the old city of Damascus, is one of the largest and oldest mosques in the world. It is considered the fourth-holiest place in Islam.<br/>"+
"After the Arab conquest of Damascus in 634, the mosque was built on the site of a Christian basilica dedicated to John the Baptist (Yahya). The mosque holds a shrine which today may still contain the head of John the Baptist, honored as a prophet by both Christians and Muslims alike, and is believed to be the place where Isa (Jesus) will return at the End of Days. The tomb of Saladin stands in a small garden adjoining the north wall of the mosque.<br/>"+
"Damascus was besieged and captured by Muslim Arab forces led by Khalid ibn al-Walid in 634. Decades later, the Islamic Caliphate came under the rule of the Umayyad dynasty, which chose Damascus to be the administrative capital of the Muslim world. The sixth Umayyad caliph, al-Walid I (r. 705–715), commissioned the construction of a mosque on the site of the Byzantine cathedral in 706. Prior to this, the cathedral was still in use by the local Christians, but a prayer room (musalla) for Muslims had been constructed on the southeastern part of the building. The construction of the mosque completely altered the layout of the building. The new house of worship was meant to serve as a large congregational mosque for the citizens of Damascus and as a tribute to the city. The mosque was completed in 715, shortly after the al-Walid's death."

var alabasterDesc = "The great Mosque of Muhammad Ali Pasha or Alabaster Mosque (Arabic: مسجد محمد علي, Turkish: Mehmet Ali Paşa Camii) is a mosque situated in the Citadel of Cairo in Egypt and commissioned by Muhammad Ali Pasha between 1830 and 1848. Situated on the summit of the citadel, this Ottoman mosque, the largest to be built in the first half of the 19th century, is, with its animated silhouette and twin minarets, the most visible mosque in Cairo. The mosque was built in memory of Tusun Pasha, Muhammad Ali's oldest son, who died in 1816. This great mosque, along with the citadel, is one of the landmarks and tourist attractions of Cairo and is one of the first features to be seen when approaching the city from no matter which side.<br/>"+
"The mosque was built on the site of old Mamluk buildings in Cairo's Citadel between 1830 and 1848, although not completed until the reign of Said Pasha in 1857. The architect was Yusuf Bushnak from Istanbul and its model was the Yeni Mosque[1][2] in that city. The ground on which the mosque was erected was built with debris from the earlier buildings of the Citadel.<br/>"+
"Before completion of the mosque, the alabastered panels from the upper walls were taken away and used for the palaces of Abbas I. The stripped walls were clad with wood painted to look like marble. In 1899 the mosque showed signs of cracking and some inadequate repairs were undertaken. Muhammad Ali Pasha was buried in a tomb carved from Carrara marble, in the courtyard of the mosque.";

var malasiaDesc = "The National Mosque of Malaysia is located in Kuala Lumpur. It has a capacity of 15,000 people and is situated among 13 acres (53,000 m2) of beautiful gardens. The original structure was designed by a three-person team from the Public Works Department - UK architect Howard Ashley, and Malaysians Hisham Albakri and Baharuddin Kassim. The mosque is a bold and modern approach in reinforced concrete, symbolic of the aspirations of a then newly-independent Malaysia.<br/>"+
"Its key features are a 73-metre-high minaret and an 16-pointed star concrete main roof. The umbrella, synonymous with the tropics, is featured conspicuously - the main roof is reminiscent of an open umbrella, the minaret's cap a folded one. The folded plates of the concrete main roof is a creative solution to achieving the larger spans required in the main gathering hall. Reflecting pools and fountains spread throughout the compound.";

var madrasaDesc = "The Madrasa Bou Inania (also Bu Inaniya, المدرسة أبو عنانية بفاس) is a madrasa in Fes, Morocco, founded in AD 1351–56 by the Abu Inan Faris, who also founded the Madrasa Bou Inania in Meknes. It is widely acknowledged as an excellent example of Marinid architecture.<br/>"+
"The name 'Bou Inania' comes from the first part of the sultan's name 'Abou Inan'. The madrasa functioned both as an educational institute and as a congregational mosque.<br/>"+
"This is the only madrasa in Fes with a minaret.Opposite the main doorway of the madrasa is the entrance to the dar al-wudu (ablutions house). Left and right of the central court there are class rooms.<br/>"+
"According to history, religious leaders of the Karaouine Mosque advised Abu Inan Faris to build this madrasa. It was the last madrasa to be built by the Marinids. The madrasa became one of the most important religious institutions of Fes and Morocco, and gained the status of Grand Mosque.<br/>"+
"The madrasa was renovated in the 18th century. During the reign of Sultan Mulay Sliman, entire sections were reconstructed. In the 20th century, major restoration work was performed on the load-bearing structure, the plaster, wood and decorations.<br/>"+
"The madrasa is one of the few religious places in Morocco that is accessible for non-Islamic visitors. Opposite the Madrasa Bou Inania is the Dar al-Magana, a wall with a hydraulic clock that was built in relation to the madrasa.";

var sehitlikDesc = "The Sehitlik Mosque ( Turkish  Türk Berlin Sehitlik Camii ) in Berlin at the historic Turkish cemetery at Columbia dam in the Neukölln district of the Turkish-Islamic Union for Religious Affairs established (DITIB). Her name took over the mosque by the Turkish cemetery, which was already created in 1863 as diplomats cemetery. The name Şehit isderived from Sehitlik here means graveyard.<br/>"+
"The Mosque is the Muslims of the neighboring districts, especially Neukölln and Kreuzberg as a place of prayer, the prayer language is mainly English, depending on the occasion and Arabic. In addition to the mosque also hosts most funeral ceremonies of the Islamic community in Berlin, the dead are then on the landscape cemetery Gatow transferred or in the home of the deceased, as the Turkish cemetery next to the mosque, as well as the Muslim grave fields of the new garrison cemetery are busy.<br/>"+
"Since the mosque next to the religious and social functions and serves as a community center, there is space for this purpose.<br/>"+
"As an architectural example of the mosque served the Ottoman architecture of the 16th and 17 Century. This period was marked by Mimar Sinan , struck with the classical Ottoman architecture reached its peak. The period lasted until the early 18th Century, when European influences were more on the Ottoman architecture.";

var package = {"starter":[{name:"Hagia Sophia",image:"hagiasofia", description:hagiasofiaDesc},{name:"The Umayyad Mosque",image:"umayyad", description:umayyadDesc},{name:"Sehitlik Mosque",image:"sehitlik", description:sehitlikDesc},{name:"Madrasa Bou Inania",image:"madrasa", description:madrasaDesc},{name:"National Mosque of Malasia",image:"malasia", description:malasiaDesc},{name:"Alabaster Mosque",image:"alabaster", description:alabasterDesc}]};